- id: nomad-validate
  name: Nomad validate
  description: Validates all Nomad configuration files.
  require_serial: true
  entry: hooks/nomad_validate.py
  language: python
  files: (\.nomad|\.job)$
