- id: nomad_validate
  name: Nomad validate
  description: Validates all Nomad configuration files.
  require_serial: true
  entry: hooks/nomad_validate.sh
  language: script
  files: (\.nomad|\.job)$
